### Importación de datos

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

#1. Análisis de facturación

In [ ]:
from IPython.display import display
facturacion_data = []
for nombre, df in tiendas.items():
  facturacion_data.append({
      'tienda': nombre,
      'facturacion total': df['Precio'].sum()
  })
facturacion = pd.DataFrame(facturacion_data)
display(facturacion)

     tienda  facturacion total
0  Tienda 1       1.150880e+09
1  Tienda 2       1.116344e+09
2  Tienda 3       1.098020e+09
3  Tienda 4       1.038376e+09

# 2. Ventas por categoría

In [ ]:
categoria_mas_popular_data = []
for nombre, df in tiendas.items():
  categoria_mas_popular_data.append({
      'tienda': nombre,
      'categoría más popular': df['Categoría del Producto'].mode()[0]
  })
  categoria_mas_popular = pd.DataFrame(categoria_mas_popular_data)
display(categoria_mas_popular)

     tienda categoría más popular
0  Tienda 1               Muebles
1  Tienda 2               Muebles
2  Tienda 3               Muebles
3  Tienda 4               Muebles

# 3. Calificación promedio de la tienda

In [ ]:
promedio_calificacion_data = []
for nombre, df in tiendas.items():
  promedio_calificacion_data.append({
      'tienda': nombre,
      'promedio de calificación': df['Calificación'].mean()
      })
promedio_calificacion = pd.DataFrame(promedio_calificacion_data)
display(promedio_calificacion)

     tienda  promedio de calificación
0  Tienda 1                  3.976685
1  Tienda 2                  4.037304
2  Tienda 3                  4.048326
3  Tienda 4                  3.995759

# 4. Productos más y menos vendidos

In [ ]:
productos_vendidos_data = []
for nombre, df in tiendas.items():
  product_counts = df['Producto'].value_counts()
  productos_vendidos_data.append({
      'tienda': nombre,
      'producto más vendido': product_counts.idxmax(),
      'cantidad más vendida': product_counts.idxmin()
  })
  productos_mas_vendidos = pd.DataFrame(productos_vendidos_data)
display(productos_mas_vendidos)

     tienda       producto más vendido       cantidad más vendida
0  Tienda 1                 Microondas  Auriculares con micrófono
1  Tienda 2  Iniciando en programación              Juego de mesa
2  Tienda 3              Kit de bancas    Bloques de construcción
3  Tienda 4                   Cama box         Guitarra eléctrica

# 5. Envío promedio por tienda

In [ ]:
costo_envio_promedio_data = []
for nombre, df in tiendas.items():
  costo_envio_promedio_data.append({
      'tienda': nombre,
      'costo envio promedio': df['Costo de envío'].mean()
  })
  costo_envio_promedio = pd.DataFrame(costo_envio_promedio_data)
display(costo_envio_promedio)

     tienda  costo envio promedio
0  Tienda 1          26018.609580
1  Tienda 2          25216.235693
2  Tienda 3          24805.680373
3  Tienda 4          23459.457167

### 6. Resumen

In [ ]:
tiendas = {
  'Tienda 1': tienda,
  'Tienda 2': tienda2,
  'Tienda 3': tienda3,
  'Tienda 4': tienda4
}
resumen = facturacion.merge( categoria_mas_popular, on='tienda').merge(promedio_calificacion, on='tienda').merge(productos_mas_vendidos, on='tienda').merge(costo_envio_promedio, on='tienda')
display(resumen)

,tienda,facturacion total,categoría más popular,promedio de calificación,producto más vendido,cantidad más vendida,costo envio promedio
0,Tienda 1,1.150880e+09,Muebles,3.976685,Microondas,Auriculares con micrófono,26018.609580
1,Tienda 2,1.116344e+09,Muebles,4.037304,Iniciando en programación,Juego de mesa,25216.235693
2,Tienda 3,1.098020e+09,Muebles,4.048326,Kit de bancas,Bloques de construcción,24805.680373
3,Tienda 4,1.038376e+09,Muebles,3.995759,Cama box,Guitarra eléctrica,23459.457167